### ISSUE TITLE
RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by zhangchunlin** [limodou/uliweb3#16]
There are codes in uliweb3 that "raise StopIteration" which from py3.5 converted into RunTimeError because of PEP479(https://www.python.org/dev/peps/pep-0479), will cause exception "RuntimeError: generator raised StopIteration" when iteratoring generators.
```
Traceback (most recent call last):
  File "/home/zhangclb/oss/uliweb3/uliweb/orm/__init__.py", line 3288, in __iter__
    raise StopIteration
StopIteration
```

**Comment by limodou** [comment]
In 3.6 not found this issue, so just close it.
