### ISSUE TITLE
Hang when no auth request invoke werkzeug.formparser.parse_form_data in views for file upload

### ISSUE THREAD

**Issue by zhangchunlin** [limodou/uliweb3#56]
Reason: in https://github.com/limodou/uliweb3/blob/master/uliweb/contrib/session/middle_session.py#L38 , if no auth in request, uliweb/contrib/session/middle_session will invoke request.values.get(), which will invoke werkzeug.formparser.parse_form_data(), but if we want to invoke werkzeug.formparser.parse_form_data() **again** in views, the function call will hang when there is a file upload.
smallest example project: [upload_test.zip](https://github.com/limodou/uliweb3/files/7725428/upload_test.zip)

**Comment by limodou** [comment]
Fixed #e64578c
